"""empty message

Revision ID: b4009ca6bfa5
Revises: 
Create Date: 2022-03-16 17:00:29.688706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4009ca6bfa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_property',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('bathrooms', sa.String(length=2), nullable=True),
    sa.Column('bedrooms', sa.String(length=2), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('prop_type', sa.String(length=9), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_property_photo'), 'user_property', ['photo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_property_photo'), table_name='user_property')
    op.drop_table('user_property')
    # ### end Alembic commands ###
